# use containter-based infastructured
# intended to fix:
#   NoMethodError: undefined method `spec' for nil:NilClass
# https://github.com/bundler/bundler/issues/3558
sudo: false

language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.3
  - 2.3.0

matrix:
  # Do not run tests with default Gemfile. We don't have it
  exclude:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.2.3
    - rvm: 2.3.0
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/test-unit.bundled.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 1.8.7
      gemfile: gemfiles/rspec.latest.gemfile
      script: bundle exec rake spec
    - rvm: 1.9.3
      gemfile: gemfiles/minitest.bundled.gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 1.9.3
      gemfile: gemfiles/rspec.latest.gemfile
      script: bundle exec rake spec
    - rvm: 2.2.3
      gemfile: gemfiles/test-unit.latest.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/minitest.latest.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/rspec.latest.gemfile
      script: bundle exec rake spec
    - rvm: 2.3.0
      gemfile: gemfiles/test-unit.latest.gemfile
      script: bundle exec rake test
    - rvm: 2.3.0
      gemfile: gemfiles/minitest.latest.gemfile
      script: bundle exec rake test
    - rvm: 2.3.0
      gemfile: gemfiles/rspec.latest.gemfile
      script: bundle exec rake spec
