language: ruby

# rvm: and gemfile: below define build matrix
rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.2
  - 2.2.3
gemfile:
  # Old gems support
  - gemfiles/old-rubies.gemfile
  - gemfiles/rspec.2.99.gemfile
  - gemfiles/minitest.4.7.5.gemfile
  # Latest gems
  - gemfiles/minitest.gemfile
  - gemfiles/test-unit.gemfile
  - gemfiles/rspec.gemfile

# Execute Ruby RSpec and Test::Unit tests
script:
  - bundle exec rake test
  - bundle exec rspec test

# Travis does not support whitelist to specify build matrix
# It only gives the way to include/exclude some builds from
# already populated matrix configured above
# To emulate whitelist we erase build matrix for all ruby
# versions and include builds we need
matrix:
  exclude:
    - rvm: 1.8.7
    - rvm: 1.9.3
    - rvm: 2.2.2
    - rvm: 2.2.3
  # Fill matrix
  include:
    - rvm: 1.8.7
      gemfile: gemfiles/old-rubies.gemfile
      # test latest 1.8.7 test/unit and latest rspec
    - rvm: 1.8.7
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 1.9.3
      gemfile: gemfiles/old-rubies.gemfile
      # test latest 1.8.7 test/unit and latest rspec
    - rvm: 1.9.3
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.2
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.2
      gemfile: gemfiles/minitest.4.7.5.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/minitest.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/test-unit.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/rspec.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.3
      gemfile: gemfiles/rspec.2.99.gemfile
      script: bundle exec rspec test
    - rvm: 2.2.3
      gemfile: gemfiles/minitest.4.7.5.gemfile
      script: bundle exec rake test
    - rvm: 2.2.2
      gemfile: gemfiles/minitest.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/test-unit.gemfile
      script: bundle exec rake test
    - rvm: 2.2.3
      gemfile: gemfiles/rspec.gemfile
      script: bundle exec rspec test
