language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.2.2
gemfile:
  - Gemfile
  - gemfiles/minitest.4.7.5.gemfile
script:
  - bundle exec rake test
  - bundle exec rspec test
matrix:
  include:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.3
      gemfile: Gemfile
    - rvm: 2.2.2
      gemfile: gemfiles/minitest.4.7.5.gemfile
